[package]
name = "RPS"
version = "0.0.0"

[addresses]
StarcoinFramework = "0x1"
SFC = "0x6ee3f577c8da207830c31e1f0abb4244"
admin = "0xd7313b057d5679de1972d5c5a7f466db"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "cf1deda180af40a8b3e26c0c7b548c4c290cd7e7" }
starcoin-framework-commons = { git = "https://github.com/starcoinorg/starcoin-framework-commons.git", rev = "e7f538175a5f50a97207692569b6631a87ee08cc" }
